version: 2
updates:
  # Maintain GitHub Actions (Checkout, Dependency Review, etc.)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain npm packages for the mev lab
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Protect against breaking proto issues
    # ignore:
    #  - dependency-name: "protobufjs"
    #    versions: [">= 7.0.0"]
