# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # Root directory logic
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"  
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
