name: "Dependency Review"

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run dependency review
        uses: github/dependency-review-action@v4
        with:
          security-severity-threshold: 'high'
