name: PHP CI

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: vendor/bin/phpunit --log-junit tests/results/test-results.xml
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: tests/results/test-results.xml
    - name: Display test results
      if: failure()
      run: cat tests/results/test-results.xml
